name: Firebase Deploy
on:
  pull_request:
    branches:
      - master

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          configuration-path: ".github/workflows/auto_assign.yml"
          